---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    # - name: "wait 600 seconds for target connection to become reachable/usable."
    #   wait_for_connection:
    #     # delay: 1
    #     # timeout: 600
    - name: "install python for Ansible."
      become: true
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false
  # Get the environment variables from CircleCI and add to the EC2 instance
    - name: Set environment variables on EC2 instance
      become: true
      shell: |
        export TYPEORM_CONNECTION={{ lookup('env', 'TYPEORM_CONNECTION')}}
        export TYPEORM_ENTITIES={{ lookup('env', 'TYPEORM_ENTITIES')}}
        export TYPEORM_HOST={{ lookup('env', 'TYPEORM_HOST')}}
        export TYPEORM_PORT=5432
        export TYPEORM_USERNAME={{ lookup('env', 'TYPEORM_USERNAME')}}
        export TYPEORM_PASSWORD={{ lookup('env', 'TYPEORM_PASSWORD')}}
        export TYPEORM_DATABASE={{ lookup('env', 'TYPEORM_DATABASE')}}
        export TYPEORM_MIGRATIONS={{ lookup('env', 'TYPEORM_MIGRATIONS')}}
        export TYPEORM_MIGRATIONS_DIR={{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}
    - name: Add environment variables to /etc/environment
      become: true
      lineinfile:
        path: /etc/environment
        line: "{{ item }}"
        insertafter: EOF
      with_items:
        - "TYPEORM_CONNECTION={{ lookup('env', 'TYPEORM_CONNECTION') }}"
        - "TYPEORM_ENTITIES={{ lookup('env', 'TYPEORM_ENTITIES') }}"
        - "TYPEORM_HOST={{ lookup('env', 'TYPEORM_HOST') }}"
        - "TYPEORM_PORT=5432"
        - "TYPEORM_USERNAME={{ lookup('env', 'TYPEORM_USERNAME') }}"
        - "TYPEORM_PASSWORD={{ lookup('env', 'TYPEORM_PASSWORD') }}"
        - "TYPEORM_DATABASE={{ lookup('env', 'TYPEORM_DATABASE') }}"
        - "TYPEORM_MIGRATIONS={{ lookup('env', 'TYPEORM_MIGRATIONS') }}"
        - "TYPEORM_MIGRATIONS_DIR={{ lookup('env', 'TYPEORM_MIGRATIONS_DIR') }}"
  roles:
    - configure-server
    - configure-prometheus-node-exporter