---
- name: Extract artifact
  become: true
  unarchive:
    src: "/root/project/artifact.tar.gz"
    dest: "./"
    remote_src: false
    extra_opts: "--no-same-owner"

- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes
    
- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

# - name: Stop existing PM2 process
#   become: true
#   shell: pm2 stop default

- name: Start app with PM2
  become: true
  shell: |
    cd ./
    pm2 start npm --name "my-app" -- start
