---
- name: Extract artifact
  become: true
  unarchive:
    src: "backend/dist/artifact.tar.gz"
    dest: "./"
    remote_src: true
    copy: false
    extra_opts: "--no-same-owner"

- name: Install dependencies
  become: true
  shell: |
    cd ./
    npm install

- name: Stop existing PM2 process
  become: true
  shell: pm2 stop default

- name: Start app with PM2
  become: true
  shell: |
    cd ./
    pm2 start npm --name "my-app" -- start
